plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aalamstudio.compiler'
    compileSdk 34

    defaultConfig {
        applicationId "com.aalamstudio.compiler"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        ndk { abiFilters 'arm64-v8a', 'armeabi-v7a' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            pickFirsts += ['META-INF/**']
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}

dependencies {
    implementation 'org.eclipse.jdt:ecj:3.12.3'
    implementation 'com.android.tools:r8:8.2.33'
    implementation 'com.android.tools.build:apksig:8.2.2'
}
